### ISSUE TITLE
Should be changeable the `type` attribute of input tag.

### ISSUE THREAD

**Issue by tsumac** [cam-inc/viron#332]
## Overview (Required)

it's very inconvenient that you not changeable the type attribute.  
for examples,  
```json
{
  "type": "string",
  "description": "title",
  "required": true,
  "maxLength": 100,
  "minLength": 10,
  "pattern": "/^[a-zA-Z]*$/",
  "attributes": {
    "type": "datetime-local"
  }
}
```

## Links
-

## Screenshot
-

**Comment by cathcheeno** [comment]
@tsumac 
Do you mean you want to change the `type` attribute of `input` tag like below??

```
<input type="datetime-local" />
```

**Comment by tsumac** [comment]
@cathcheeno you are right. do not you have trouble, if you can not change it?

**Comment by cathcheeno** [comment]
I'm sorry I don't have a plan to add `attributes` key. That is because the Viron follows the [Open API Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) and adding `attributes` key is out of rule.

However there is an issue of #269 which will solve your problem by using`format` key.(Instead of adding `attributes`)

These are some hints related to `format` and its value.
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#dataTypeFormat
- https://tools.ietf.org/html/rfc3339#section-5.6

PR is welcomed :)
Or wait #269 to be implemented.
